# Generated by Django 5.2.4 on 2025-07-18 16:34

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Local de Estoque',
                'verbose_name_plural': 'Locais de Estoque',
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('batch_code', models.CharField(blank=True, max_length=64, verbose_name='Lote')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('unit_of_measure', models.CharField(choices=[('un', 'Unidade'), ('g', 'Grama'), ('kg', 'Quilograma'), ('ml', 'Mililitro'), ('l', 'Litro'), ('fatia', 'Fatia')], max_length=16, verbose_name='Unidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('production_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionbatch', verbose_name='Lote de Produção')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='stock.stocklocation')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
                'ordering': ['content_type', 'expiration_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalStockMovement',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('movement_type', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('transferencia', 'Transferência'), ('ajuste', 'Ajuste'), ('insumo_producao', 'Consumo de Produção'), ('producao_final', 'Produto Acabado')], max_length=32, verbose_name='Tipo de movimento')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('adjustment_reason', models.CharField(blank=True, choices=[('erro_inventario', 'Erro de Inventário'), ('avaria', 'Avaria'), ('furto', 'Furto'), ('amostra', 'Amostra Técnica'), ('outro', 'Outro')], max_length=32, null=True, verbose_name='Motivo de ajuste')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referência externa')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.productionorder', verbose_name='Ordem de Produção Relacionada')),
                ('stock_item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.stockitem')),
                ('destination_location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.stocklocation')),
                ('source_location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.stocklocation')),
            ],
            options={
                'verbose_name': 'historical Movimentação de Estoque',
                'verbose_name_plural': 'historical Movimentações de Estoque',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('transferencia', 'Transferência'), ('ajuste', 'Ajuste'), ('insumo_producao', 'Consumo de Produção'), ('producao_final', 'Produto Acabado')], max_length=32, verbose_name='Tipo de movimento')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('adjustment_reason', models.CharField(blank=True, choices=[('erro_inventario', 'Erro de Inventário'), ('avaria', 'Avaria'), ('furto', 'Furto'), ('amostra', 'Amostra Técnica'), ('outro', 'Outro')], max_length=32, null=True, verbose_name='Motivo de ajuste')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referência externa')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_movements', to='stock.stocklocation')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionorder', verbose_name='Ordem de Produção Relacionada')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_movements', to='stock.stocklocation')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock.stockitem')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StockThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField()),
                ('min_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade mínima')),
                ('alert_enabled', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Alerta de Estoque',
                'verbose_name_plural': 'Alertas de Estoque',
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
