# Generated by Django 5.2.4 on 2025-07-18 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('supplies', '0004_supplyingredientdetail_supplynutritioninfo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockitem',
            options={'ordering': ['supply_item', 'expiration_date'], 'verbose_name': 'Estoque', 'verbose_name_plural': 'Estoques'},
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='object_id',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='supply_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='supplies.supplyitem', verbose_name='Item de Insumo'),
        ),
    ]
