# Generated by Django 5.2.4 on 2025-07-18 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stockitem_options_and_more'),
        ('supplies', '0004_supplyingredientdetail_supplynutritioninfo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockthreshold',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stockthreshold',
            name='supply_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threshold', to='supplies.supplyitem', verbose_name='Item de Insumo'),
        ),
        migrations.RemoveField(
            model_name='stockthreshold',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='stockthreshold',
            name='object_id',
        ),
    ]
