# Generated by Django 5.2.4 on 2025-07-18 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stockthreshold_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
