# Generated by Django 5.2.4 on 2025-07-18 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stocklocation_created_at_stocklocation_updated_at'),
        ('supplies', '0004_supplyingredientdetail_supplynutritioninfo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockitem',
            options={'verbose_name': 'Estoque', 'verbose_name_plural': 'Estoques'},
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='batch_code',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='supply_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='supplies.supplybatch', verbose_name='Lote de Insumo'),
        ),
    ]
