# Generated by Django 5.2.4 on 2025-07-18 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_stockitem_options_remove_stockitem_batch_code_and_more'),
        ('supplies', '0004_supplyingredientdetail_supplynutritioninfo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockitem',
            options={'ordering': ['supply_item__name', 'supply_batch__expiration_date'], 'verbose_name': 'Estoque', 'verbose_name_plural': 'Estoques'},
        ),
        migrations.AlterField(
            model_name='historicalstockmovement',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='stock.stocklocation', verbose_name='Local de Armazenamento'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Atual'),
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='stockthreshold',
            name='alert_enabled',
            field=models.BooleanField(default=True, verbose_name='Alerta Ativo'),
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('supply_batch', 'location')},
        ),
    ]
