# Generated by Django 5.2.4 on 2025-07-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_stockitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstockmovement',
            name='adjustment_reason',
            field=models.CharField(blank=True, choices=[('erro_inventario', 'Erro de Inventário'), ('avaria', 'Avaria'), ('furto', 'Furto'), ('amostra', 'Amostra Técnica'), ('ajuste_admin', 'Ajuste Manual via Admin'), ('outro', 'Outro')], max_length=32, null=True, verbose_name='Motivo de ajuste'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='adjustment_reason',
            field=models.CharField(blank=True, choices=[('erro_inventario', 'Erro de Inventário'), ('avaria', 'Avaria'), ('furto', 'Furto'), ('amostra', 'Amostra Técnica'), ('ajuste_admin', 'Ajuste Manual via Admin'), ('outro', 'Outro')], max_length=32, null=True, verbose_name='Motivo de ajuste'),
        ),
    ]
