# Generated by Django 5.2.4 on 2025-07-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_historicalstockmovement_adjustment_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstockmovement',
            name='after_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Estoque Depois'),
        ),
        migrations.AddField(
            model_name='historicalstockmovement',
            name='before_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Estoque Antes'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='after_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Estoque Depois'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='before_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Estoque Antes'),
        ),
    ]
