# Generated by Django 5.2.4 on 2025-07-18 16:34

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cakes', '0004_remove_cakeimage_url_cakeimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProductionOrder',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade a produzir')),
                ('scheduled_date', models.DateField(verbose_name='Data programada')),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('em_execucao', 'Em execução'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='planejada', max_length=32, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Início da produção')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Conclusão da produção')),
                ('produced_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade produzida')),
                ('waste_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Perda')),
                ('rework_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Retrabalho')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cake', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cakes.cake')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'historical Ordem de Produção',
                'verbose_name_plural': 'historical Ordens de Produção',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade a produzir')),
                ('scheduled_date', models.DateField(verbose_name='Data programada')),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('em_execucao', 'Em execução'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='planejada', max_length=32, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Início da produção')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Conclusão da produção')),
                ('produced_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade produzida')),
                ('waste_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Perda')),
                ('rework_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Retrabalho')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakes.cake')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Ordem de Produção',
                'verbose_name_plural': 'Ordens de Produção',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_code', models.CharField(max_length=50, verbose_name='Código do lote')),
                ('produced_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantidade produzida')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Início')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Conclusão')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='production.productionorder')),
            ],
            options={
                'verbose_name': 'Lote de Produção',
                'verbose_name_plural': 'Lotes de Produção',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_type', models.CharField(choices=[('massa', 'Preparar Massa'), ('assar', 'Assar'), ('rechear', 'Rechear'), ('cobrir', 'Cobrir/Decorar'), ('embalar', 'Embalar'), ('outro', 'Outro')], max_length=32, verbose_name='Etapa')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Início')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Conclusão')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração (min)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Concluída')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='production.productionorder')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Etapa da Produção',
                'verbose_name_plural': 'Etapas da Produção',
                'ordering': ['step_type', 'started_at'],
            },
        ),
    ]
