# Generated by Django 5.2.4 on 2025-07-16 18:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=32, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='supplies/images/', verbose_name='Imagem')),
                ('barcode', models.CharField(blank=True, max_length=64, verbose_name='Código de barras')),
                ('unit_of_measure', models.CharField(choices=[('un', 'Unidade'), ('g', 'Grama'), ('kg', 'Quilograma'), ('ml', 'Mililitro'), ('l', 'Litro'), ('fatia', 'Fatia')], max_length=16, verbose_name='Unidade de medida')),
                ('category', models.CharField(choices=[('base', 'Base do Bolo'), ('filling', 'Recheio'), ('topping', 'Cobertura'), ('flavoring', 'Aromatizante'), ('coloring', 'Corante'), ('decoration', 'Decoração'), ('garnish', 'Enfeite Comestível'), ('mold', 'Forma / Molde'), ('packaging', 'Embalagem'), ('label', 'Etiqueta'), ('sticker', 'Adesivo'), ('cleaning', 'Produto de Limpeza'), ('epi', 'Equipamento de Proteção'), ('utensil', 'Utensílio'), ('tool', 'Ferramenta Técnica'), ('raw_material', 'Matéria-prima Diversa'), ('additive', 'Aditivo'), ('promo_item', 'Item Promocional'), ('other', 'Outro')], max_length=32, verbose_name='Categoria')),
                ('origin_country', models.CharField(blank=True, max_length=64, verbose_name='País de origem')),
                ('regulatory_code', models.CharField(blank=True, max_length=64, verbose_name='Código regulatório')),
                ('expiration_control', models.BooleanField(default=False, verbose_name='Controla validade')),
                ('batch_control', models.BooleanField(default=False, verbose_name='Controla lote')),
                ('is_ingredient', models.BooleanField(default=False, help_text='Use apenas para itens comestíveis e aplicáveis em receitas.', verbose_name='Pode ser usado como ingrediente?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Item de Suprimento',
                'verbose_name_plural': 'Itens de Suprimentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplyBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=64, verbose_name='Código do lote')),
                ('expiration_date', models.DateField(verbose_name='Data de validade')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('supply_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='supplies.supplyitem', verbose_name='Item de Suprimento')),
            ],
            options={
                'verbose_name': 'Lote de Suprimento',
                'verbose_name_plural': 'Lotes de Suprimentos',
                'ordering': ['-expiration_date'],
                'unique_together': {('supply_item', 'batch_code')},
            },
        ),
    ]
