# Generated by Django 5.2.4 on 2025-07-16 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='supplies/images/', verbose_name='Imagem')),
                ('image_type', models.CharField(choices=[('principal', 'Principal'), ('embalagem', 'Foto da Embalagem'), ('rotulo', 'Rótulo / Informações Nutricionais'), ('detalhe', 'Detalhe Visual'), ('contexto', 'Uso no Contexto')], max_length=20, verbose_name='Tipo')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Imagem de capa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('supply_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='supplies.supplyitem', verbose_name='Suprimento')),
            ],
            options={
                'verbose_name': 'Imagem de Suprimento',
                'verbose_name_plural': 'Imagens de Suprimento',
                'ordering': ['-is_cover', 'image_type'],
            },
        ),
    ]
