# Generated by Django 5.2.4 on 2025-07-16 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_supplyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyitem',
            name='image',
        ),
    ]
