# Generated by Django 5.2.4 on 2025-07-17 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_remove_supplyitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyIngredientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_list', models.TextField(blank=True, verbose_name='Ingredientes')),
                ('contains_gluten', models.BooleanField(default=False, verbose_name='Contém glúten?')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='É vegano?')),
                ('warnings', models.TextField(blank=True, verbose_name='Advertências de consumo')),
                ('supply_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_detail', to='supplies.supplyitem', verbose_name='Item de Suprimento')),
            ],
            options={
                'verbose_name': 'Composição e Advertências',
                'verbose_name_plural': 'Composições e Advertências',
            },
        ),
        migrations.CreateModel(
            name='SupplyNutritionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_size', models.CharField(max_length=64, verbose_name='Porção')),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Calorias')),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Proteínas (g)')),
                ('fat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Gorduras Totais (g)')),
                ('saturated_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Gorduras Saturadas (g)')),
                ('trans_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Gorduras Trans (g)')),
                ('carbohydrates', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Carboidratos (g)')),
                ('sugars', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Açúcares (g)')),
                ('fiber', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Fibras (g)')),
                ('sodium', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Sódio (mg)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('supply_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_info', to='supplies.supplyitem')),
            ],
            options={
                'verbose_name': 'Informação Nutricional',
                'verbose_name_plural': 'Informações Nutricionais',
            },
        ),
        migrations.CreateModel(
            name='SupplyProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nome')),
                ('tag_type', models.CharField(choices=[('catalog_category', 'Categoria de Catálogo'), ('department', 'Departamento'), ('subcategory', 'Subcategoria'), ('size', 'Tamanho'), ('type', 'Tipo'), ('format', 'Formato'), ('form_type', 'Tipo de Forma'), ('seasonality', 'Sazonalidade'), ('color', 'Cor'), ('brand', 'Marca'), ('pattern', 'Estampa')], max_length=32, verbose_name='Tipo de Tag')),
            ],
            options={
                'verbose_name': 'Tag de Produto',
                'verbose_name_plural': 'Tags de Produtos',
                'ordering': ['tag_type', 'name'],
                'unique_together': {('name', 'tag_type')},
            },
        ),
        migrations.AddField(
            model_name='supplyitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='supply_items', to='supplies.supplyproducttag'),
        ),
    ]
