# Generated by Django 5.2.4 on 2025-07-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0004_supplyingredientdetail_supplynutritioninfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplybatch',
            name='stock_entry_created',
            field=models.BooleanField(default=False, verbose_name='Entrada no estoque realizada?'),
        ),
    ]
