# Generated by Django 5.2.4 on 2025-07-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0005_supplybatch_stock_entry_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplybatch',
            name='stock_entry_created',
            field=models.BooleanField(default=False, help_text='Indica se esse lote já foi lançado no estoque.', verbose_name='Entrada de estoque criada'),
        ),
    ]
