# Generated by Django 5.2.4 on 2025-07-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0006_alter_supplybatch_stock_entry_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplybatch',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Marque como inativo para impedir movimentações e entradas no estoque.', verbose_name='Ativo'),
        ),
    ]
