# Generated by Django 5.2.4 on 2025-07-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakesize',
            name='description',
            field=models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], default='medio', max_length=20, verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='cakesize',
            name='serves',
            field=models.PositiveIntegerField(verbose_name='Serve (pessoas)'),
        ),
    ]
