# Generated by Django 5.2.4 on 2025-07-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_alter_cakesize_description_alter_cakesize_serves'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakeimage',
            name='is_cover',
            field=models.BooleanField(default=False, verbose_name='Imagem de capa'),
        ),
    ]
