# Generated by Django 5.2.4 on 2025-07-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0003_cakeimage_is_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cakeimage',
            name='url',
        ),
        migrations.AddField(
            model_name='cakeimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cakes/', verbose_name='Imagem'),
        ),
    ]
